import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  createTheme,
  DEFAULT_THEME,
  DEFAULT_THEME_COLORS,
  generateThemeCssProperties,
  THEME_CSS_CLASSES,
  TW_THEME,
} from './theme';

describe('theme', () => {
  describe('TW_THEME InjectionToken', () => {
    it('should be defined', () => {
      expect(TW_THEME).toBeDefined();
      expect(TW_THEME.toString()).toContain('TW_THEME');
    });
  });

  describe('DEFAULT_THEME', () => {
    it('should use the default color palette', () => {
      expect(DEFAULT_THEME.name).toBe('default');
      expect(DEFAULT_THEME.colors).toBe(DEFAULT_THEME_COLORS);
    });
  });

  describe('createTheme()', () => {
    it('should merge custom colors with defaults', () => {
      const theme = createTheme({
        colors: {
          primary: { light: '#6366f1', dark: '#818cf8' },
        },
      });

      expect(theme.colors.primary).toEqual({ light: '#6366f1', dark: '#818cf8' });
      expect(theme.colors.danger).toEqual(DEFAULT_THEME_COLORS.danger);
      expect(theme.colors.background).toEqual(DEFAULT_THEME_COLORS.background);
    });

    it('should default the theme name to custom', () => {
      expect(createTheme({}).name).toBe('custom');
      expect(createTheme({ name: 'branded' }).name).toBe('branded');
    });

    it('should pass through components and custom properties', () => {
      const theme = createTheme({
        components: {
          button: { primaryBg: { light: '#111111', dark: '#222222' } },
        },
        customProperties: { 'spacing-unit': '4px' },
      });

      expect(theme.components?.button?.primaryBg).toEqual({ light: '#111111', dark: '#222222' });
      expect(theme.customProperties?.['spacing-unit']).toBe('4px');
    });
  });

  describe('generateThemeCssProperties()', () => {
    it('should generate light and dark values for semantic colors', () => {
      const { light, dark } = generateThemeCssProperties(DEFAULT_THEME);

      expect(light['--tw-color-primary']).toBe(DEFAULT_THEME_COLORS.primary.light);
      expect(dark['--tw-color-primary']).toBe(DEFAULT_THEME_COLORS.primary.dark);
    });

    it('should convert camelCase color names to kebab-case variables', () => {
      const { light } = generateThemeCssProperties(DEFAULT_THEME);

      expect(light['--tw-color-text-primary']).toBe(DEFAULT_THEME_COLORS.textPrimary.light);
      expect(light['--tw-color-surface-alt']).toBe(DEFAULT_THEME_COLORS.surfaceAlt.light);
      expect(light['--tw-color-border-focus']).toBe(DEFAULT_THEME_COLORS.borderFocus.light);
    });

    it('should generate component override variables', () => {
      const { light, dark } = generateThemeCssProperties({
        colors: {},
        components: {
          button: { primaryBg: { light: '#111111', dark: '#222222' } },
        },
      });

      expect(light['--tw-button-primary-bg']).toBe('#111111');
      expect(dark['--tw-button-primary-bg']).toBe('#222222');
    });

    it('should generate custom properties', () => {
      const { light, dark } = generateThemeCssProperties({
        colors: {},
        customProperties: {
          'spacing-unit': '4px',
          accent: { light: '#333333', dark: '#444444' },
          '--custom-var': '1rem',
        },
      });

      expect(light['--tw-spacing-unit']).toBe('4px');
      expect(dark['--tw-spacing-unit']).toBe('4px');
      expect(light['--tw-accent']).toBe('#333333');
      expect(dark['--tw-accent']).toBe('#444444');
      expect(light['--custom-var']).toBe('1rem');
    });
  });

  describe('THEME_CSS_CLASSES', () => {
    const themeCss = readFileSync(
      join(process.cwd(), 'projects/ngx-tailwindcss/src/lib/styles/theme.css'),
      'utf8'
    );

    it('should only reference variables generated by the theme or declared in theme.css', () => {
      const { light } = generateThemeCssProperties(DEFAULT_THEME);

      for (const value of Object.values(THEME_CSS_CLASSES)) {
        const match = /var\((--[\w-]+)\)/.exec(value);
        expect(match).not.toBeNull();

        const cssVar = match![1];
        const isGenerated = cssVar in light;
        const isDeclared = themeCss.includes(`${cssVar}:`);
        expect(isGenerated || isDeclared, `${value} references undeclared ${cssVar}`).toBe(true);
      }
    });

    it('should reference the generated text-primary variable', () => {
      const { light } = generateThemeCssProperties(DEFAULT_THEME);

      expect(THEME_CSS_CLASSES.textPrimary).toBe('text-[var(--tw-color-text-primary)]');
      expect(light['--tw-color-text-primary']).toBeDefined();
      expect(themeCss).toContain('--tw-color-text-primary:');
    });
  });
});
